# https://github.com/SeleniumHQ/docker-selenium

version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.19.0-20240328
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
      
  selenium-hub:
    image: selenium/hub:4.19.0-20240328
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"